### ISSUE TITLE
warpctc_tensorflow/kernels.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _ZTIN10tensorflow8OpKernelE

### ISSUE THREAD

**Issue by HawkAaron** [baidu-research/warp-ctc#119]
I've tried hundreds of times, in TF version 1.4 or 1.8, no matter how, the error was always produced as the title.

Is there anybody successed ?

**Comment by HawkAaron** [comment]
Finally, I get the right way to setup:
https://github.com/HawkAaron/warp-ctc/blob/pytorch_bindings/tensorflow_binding/setup.py

**Comment by rolai** [comment]
@HawkAaron I meet a new problem when I use your setup.py. 

gcc -pthread -B /home/lairf/miniconda2/compiler_compat -Wl,--sysroot=/ -fno-strict-aliasing -g -O2 -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -I/home/lairf/miniconda2/lib/python2.7/site-packages/tensorflow/include -I/home/lairf/Code/tensorflow -I/home/lairf/Code/warp-ctc/tensorflow_binding/../include -I/home/lairf/miniconda2/lib/python2.7/site-packages/tensorflow/include/../../external/nsync/public -I/usr/local/cuda/include -I/home/lairf/Code/warp-ctc/tensorflow_binding/include -I/home/lairf/miniconda2/include/python2.7 -c src/warpctc_op.cc -o build/temp.linux-x86_64-2.7/src/warpctc_op.o -std=c++11 -fPIC -D_GLIBCXX_USE_CXX11_ABI=1 -Wno-return-type -DWARPCTC_ENABLE_GPU
g++ -pthread -shared -B /home/lairf/miniconda2/compiler_compat -L/home/lairf/miniconda2/lib -Wl,-rpath=/home/lairf/miniconda2/lib -Wl,--no-as-needed -Wl,--sysroot=/ build/temp.linux-x86_64-2.7/src/ctc_op_kernel.o build/temp.linux-x86_64-2.7/src/warpctc_op.o -L../build -L/home/lairf/miniconda2/lib -Wl,-R/home/lairf/Code/warp-ctc/build -lwarpctc -ltensorflow_framework -lpython2.7 -o build/lib.linux-x86_64-2.7/warpctc_tensorflow/kernels.so
/home/lairf/miniconda2/compiler_compat/ld: **cannot find -ltensorflow_framework**
collect2: error: ld returned 1 exit status
error: command 'g++' failed with exit status 1

Is there any setups I missed?

**Comment by rolai** [comment]
It seems the TENSORFLOW_SRC_PATH is wrong. Now I can build it after set the path to tensorflow1.8/bazel-bin/tensorflow
But when I run **python setup.py test**, I meet a new problem!
BTW, I build from source tf1.8 with cuda 9.2, cudnn 7.1.4 and bazel 0.13.1

======================================================================
ERROR: test_ctc_loss_op (unittest.loader.ModuleImportFailure)
----------------------------------------------------------------------
ImportError: Failed to import test module: test_ctc_loss_op
Traceback (most recent call last):
  File "/home/lairf/miniconda2/lib/python2.7/unittest/loader.py", line 254, in _find_tests
    module = self._get_module_from_name(name)
  File "/home/lairf/miniconda2/lib/python2.7/unittest/loader.py", line 232, in _get_module_from_name
    __import__(name)
  File "/home/lairf/Code/warp-ctc/tensorflow_binding/tests/test_ctc_loss_op.py", line 23, in <module>
    import warpctc_tensorflow
  File "/home/lairf/Code/warp-ctc/tensorflow_binding/warpctc_tensorflow/__init__.py", line 7, in <module>
    _warpctc = tf.load_op_library(lib_file)
  File "/home/lairf/miniconda2/lib/python2.7/site-packages/tensorflow/python/framework/load_library.py", line 56, in load_op_library
    lib_handle = py_tf.TF_LoadLibrary(library_filename)
NotFoundError: /home/lairf/Code/warp-ctc/tensorflow_binding/warpctc_tensorflow/kernels.so: undefined symbol: _ZN10tensorflow7strings6StrCatERKNS0_8AlphaNumES3_S3_S3_


======================================================================
ERROR: test_warpctc_op (unittest.loader.ModuleImportFailure)
----------------------------------------------------------------------
ImportError: Failed to import test module: test_warpctc_op
Traceback (most recent call last):
  File "/home/lairf/miniconda2/lib/python2.7/unittest/loader.py", line 254, in _find_tests
    module = self._get_module_from_name(name)
  File "/home/lairf/miniconda2/lib/python2.7/unittest/loader.py", line 232, in _get_module_from_name
    __import__(name)
  File "/home/lairf/Code/warp-ctc/tensorflow_binding/tests/test_warpctc_op.py", line 3, in <module>
    from warpctc_tensorflow import ctc
  File "/home/lairf/Code/warp-ctc/tensorflow_binding/warpctc_tensorflow/__init__.py", line 7, in <module>
    _warpctc = tf.load_op_library(lib_file)
  File "/home/lairf/miniconda2/lib/python2.7/site-packages/tensorflow/python/framework/load_library.py", line 56, in load_op_library
    lib_handle = py_tf.TF_LoadLibrary(library_filename)
NotFoundError: /home/lairf/Code/warp-ctc/tensorflow_binding/warpctc_tensorflow/kernels.so: undefined symbol: _ZN10tensorflow7strings6StrCatERKNS0_8AlphaNumES3_S3_S3_


----------------------------------------------------------------------
Ran 2 tests in 0.000s

FAILED (errors=2)
Test failed: <unittest.runner.TextTestResult run=2 errors=2 failures=0>
error: Test failed: <unittest.runner.TextTestResult run=2 errors=2 failures=0>

**Comment by HawkAaron** [comment]
@rolai 
Maybe you can set TENSORFLOW_SRC_PATH to the tf installation path:
```bash
python -c 'import tensorflow as tf; print(tf)'
```
In your case, that would be `/home/lairf/miniconda2/lib/python2.7/site-packages/tensorflow`

After that run `python tests/testxxx.py` directly.

**Comment by HawkAaron** [comment]
@rolai 
If you build tf source using gcc 5 or higher version, please check this warning:
https://github.com/HawkAaron/warp-ctc/blob/pytorch_bindings/tensorflow_binding/setup.py#L66

set `TF_CXX11_ABI=1` before run `setup.py`

**Comment by rolai** [comment]
@HawkAaron 
Nice!  It fixed my problems. Thank you very much!

**Comment by dzhwinter** [comment]
Thanks for fixing this problem!
