### ISSUE TITLE
请问这个能否在windows下编译成python库

### ISSUE THREAD

**Issue by shesheshebie2** [baidu-research/warp-ctc#129]
如题，如果有的话，有无相关的教程链接

**Comment by shesheshebie2** [comment]
从以前的问题中找到了，谢谢

**Comment by Fighting-JJ** [comment]
> 从以前的问题中找到了，谢谢

  @shesheshebie2 能把那个问题贴出来么？我也打算在windows下把warp-ctc编译成python库
