### ISSUE TITLE
please look the error when I run "test_cpu"

### ISSUE THREAD

**Issue by coolshinejonson** [baidu-research/warp-ctc#19]
follow the Compilation explain, create "test_cpu"  file.
when Ｉ try to run the program, but it's error like this:
$ ./test_cpu 
./test_cpu: error while loading shared libraries: libwarpctc.so: cannot open shared object file: No such file or directory
"libwarpctc.so"  exists. What is the problem?

**Comment by ekelsen** [comment]
Can you give a little more detail?  What system are you running on and the output of ```ldd testcpu```

**Comment by sherjilozair** [comment]
Also, could you confirm whether the `build` directory contains `libwarpctc.so`? It seems to me that compilation didn't succeed and the `.so` file was just not created. Installation output could also be useful.

**Comment by Ilya-Krylov** [comment]
add build directory (where libwarpctc.so is located) to LD_LIBRARY_PATH

**Comment by coolshinejonson** [comment]
llya-Krylov, thank you for the solution. 
BTW, my system is Ubuntu 14.04.3.

**Comment by Halfish** [comment]
thanks to @Ilya-Krylov , I solved my problem by command like this on my Ubuntu 14.04.4:
```shell
export LD_LIBRARY_PATH=/home/halfish/torch/install/lib:$LD_LIBRARY_PATH
```
