### ISSUE TITLE
Gradient output from batch using torch binding

### ISSUE THREAD

**Issue by SeanNaren** [baidu-research/warp-ctc#22]
Sorry if this is answered elsewhere or blatantly obvious, but I'm not entirely sure of the formatting of the gradients after carrying out a batch like below:
```
th>acts = torch.Tensor({{0,0,0,0,0},{1,2,3,4,5},{-5,-4,-3,-2,-1},
                        {0,0,0,0,0},{6,7,8,9,10},{-10,-9,-8,-7,-6},
                        {0,0,0,0,0},{11,12,13,14,15},{-15,-14,-13,-12,-11}}):cuda()
th>labels = {{1}, {3,3}, {2,3}}
th>sizes = {1,3,3}
th>grads = torch.Tensor(acts:size())
th>gpu_ctc(acts, grads, labels, sizes)

{
  1 : 1.6094379425049
  2 : 7.355742931366
  3 : 4.938850402832
}
```

Should we expect the gradients to also be in column major formatting like how we put our multiple sequences in (i.e we would need to reverse the batching steps we did for the activation sequence with the gradients)? Thanks!

**Comment by dxyzab** [comment]
The gradients will be in the same format as the incoming activations: each gradient matrix entry will be dCTC/da_{ij} where a_{ij} is an incoming activation to CTC.

**Comment by SeanNaren** [comment]
Thanks for your reply! 

Somewhat related, I've written a simple Criterion for implementation of the library in torch:

https://github.com/SeanNaren/CTCNetworkClient/blob/master/ctc/CTCCriterion.lua

For when batching occurs I've written a transformer to and from the library:

https://github.com/SeanNaren/CTCNetworkClient/blob/master/ctc/CTCBatcher.lua

Hopefully the transformation and implementation is correct, should be based on the answer you have given me! If you have any feedback or see any issues please let me know.

If you find it useful, I will happily send a pull request to add this.

**Comment by NightFury13** [comment]
@SeanNaren : The repo you linked leads to a 404. Moved the package?

Can you tell me how does one do gradient-update using the warp-ctc? The tutorial has a line which says that "If an empty grad Tensor is passed, the gradient calculation will not be done." However, I can't find any section of doing the gradient calculation. Can you provide me with some sample code to run a fwd-bwd pass on a simple network in torch using the CTC error criterion?

**Comment by NightFury13** [comment]
Thanks to 'nnx' (https://github.com/clementfarabet/lua---nnx), the wrapping of warp-ctc as a criterion for torch models is taken care of. FYI. :)
