### ISSUE TITLE
input_lengths has the same value?

### ISSUE THREAD

**Issue by qingzew** [baidu-research/warp-ctc#24]
[here](https://github.com/baidu-research/warp-ctc/blob/670943bafdb97dfe3797c3485a9644de890e8a54/src/ctc_entrypoint.cpp#L103) ,we can see that input_lengths can have different values,  but [here](https://github.com/baidu-research/warp-ctc/blob/master/include/detail/cpu_ctc.h#L165), the code think all inpus are the same length.

is this a problem?

**Comment by ekelsen** [comment]
In the second file the loop on line 164 loops over the length of each utterance.
