### ISSUE TITLE
Meaning of N

### ISSUE THREAD

**Issue by bver** [baidu-research/warp-ctc#25]
Hello,

Could you please explain what N symbol means in README.md benchmark tables?
L, A, T dimensions are described well but I cannot find a description for N.

Sorry if I am missing something obvious.
Anyway, thank you for your work,
Pavel

**Comment by bryancatanzaro** [comment]
N is the minibatch size.

**Comment by bver** [comment]
ok, thanks.
My misunderstading was caused by "...our performance at a minibatch of 64 examples" -- I thought that minibatch size was fixed to 64.
