### ISSUE TITLE
Will you have any examples close to DeepSpeech 2?

### ISSUE THREAD

**Issue by shyamalschandra** [baidu-research/warp-ctc#26]
Will this be possible to furnish at a small scale for CTC?

**Comment by denghuiru** [comment]
I also wonder whether you can give a small example about DeepSpeech?
Thank you!

**Comment by wenkesj** [comment]
You can implement it yourself in Torch7. [This Torch binding makes it much easier here](https://github.com/clementfarabet/lua---nnx#nnx.CTCCriterion) and the community is much more active around there.

**Comment by SeanNaren** [comment]
(Shameless plug) have been working on a DeepSpeech2 implementation in Torch [here](https://github.com/SeanNaren/deepspeech.torch) using warp-ctc, might help out!

**Comment by jaredcasper** [comment]
I think sample models are beyond the scope of this repo which is just CTC and not a full framework that would run a sample model.  If we released a sample model it would be part of another project.
