### ISSUE TITLE
Building error

### ISSUE THREAD

**Issue by Jihadik** [baidu-research/warp-ctc#27]
Have you encountered the following error?
```sh
Scanning dependencies of target warpctc
Linking CXX shared library libwarpctc.so
/usr/bin/ld: cannot find -lTHC
collect2: error: ld returned 1 exit status
make[2]: *** [libwarpctc.so] Error 1
make[1]: *** [CMakeFiles/warpctc.dir/all] Error 2
make: *** [all] Error 2
```
How to overcome it?

**Comment by Jihadik** [comment]
After torch installation I additionally run `luarocks install torch`, `luarocks install cutorch` and everything was solved.

**Comment by denghuiru** [comment]
@Jihadik 
Hi，I met the same problem with you, However when i using the command “luarocks install torch”， it shows that  /root/torch/install/bin/lua: /tmp/luarocks_torch-scm-1-8931/torch7/random.lua:1: module 'cwrap' not found:
Have you met this problems yet? Please help me to solve this problem!
Thanks very much!

**Comment by Jihadik** [comment]
Try to check [this issue](https://github.com/torch/torch7/issues/47). It seems really helpful for your problem.
