### ISSUE TITLE
the installation of wrap-ctc

### ISSUE THREAD

**Issue by wqn628** [baidu-research/warp-ctc#33]
Hello,
May I kindly ask for help  on the the installation of wrap-ctc? when I install the wrap-ctc by  running "luarocks make torch_binding/rocks/warp-ctc-scm-1.rockspec" at the top level directory,one error occurs as follows:
**Missing** dependencies for warp-ctc:
torch >= 7.0

Error: Could not satisfy dependency: torch >= 7.0**
so, I don't have any idea about this.
anyone has encountered such problem? Can you give me some advices on this ?Any help would be appreciated .thanks

**Comment by NightFury13** [comment]
You need to install Torch first. 

Get started here : http://torch.ch/docs/getting-started.html

**Comment by jaredcasper** [comment]
I'll assume that installing torch has fixed the problem.
