### ISSUE TITLE
Using the torch bindings to experiment with CTC

### ISSUE THREAD

**Issue by wqn628** [baidu-research/warp-ctc#37]
Hello,
May I kindly ask for some help?while Using the torch bindings to experiment with CTC, I want to use the code to do some calculation by "  require 'cutorch'  ",however one error occurs as follows:
![image](https://cloud.githubusercontent.com/assets/17527574/16000165/4228924e-317d-11e6-98ac-a41d9e97380a.png)

And I have compiled with GPU support,standard CUDA.
While I do the experiment with CPU,the situation as follows:
![image](https://cloud.githubusercontent.com/assets/17527574/16000340/6accfb1c-317e-11e6-915c-3ebfebe35661.png)

so, I have no idea why there is difference between them .
anyone has encountered such problem? Can you give me some advices on this ?Any help would be appreciated .thanks

**Comment by wqn628** [comment]
And I have compiled with GPU support,standard CUDA.
While I do the experiment with CPU,the situation as follows:
![image](https://cloud.githubusercontent.com/assets/17527574/16000285/0a6863b0-317e-11e6-8ec1-0c0198d33db1.png)
I have no idea why there is difference between them . Any help will be appreciated,thanks

**Comment by jaredcasper** [comment]
If you are still having issues please provide more details as to what the error is.  In the screen shots you have provided it doesn't look like you have attempted to do anything with warp_ctc.  Closing this for now since its been a long time.
