### ISSUE TITLE
"gpu_ctc"  problem ?

### ISSUE THREAD

**Issue by lji72** [baidu-research/warp-ctc#39]
When I try the example,  I encounter a problem as follow.
"
th> gpu_ctc  -h
[string "_RESULT={gpu_ctc  -h}"]:1: attempt to perform arithmetic on global 'gpu_ctc' (a nil value)
stack traceback:
    [string "_RESULT={gpu_ctc  -h}"]:1: in main cheunk
    [C]: in function 'xpcall'
    /root/torch/install/share/lua/5.1/trepl/init.lua:651: in function 'repl'
    /root/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:199: in main chunk
    [C]: at 0x00406670  
"

**Comment by wenkesj** [comment]
gpu_ctc is a function, if you are using this with torch that is the equivalent to writing `gpu_ctc - h` where `h` is some variable (`nil` in this case)..

**Comment by jaredcasper** [comment]
I'll assume that using gpu_ctc correctly as a function and not as a variable resolves this issue.
