### ISSUE TITLE
test_gpu Fails!

### ISSUE THREAD

**Issue by razor1179** [baidu-research/warp-ctc#43]
I am unable to run ./test_gpu, I've copied the result of ldd test_gpu
        linux-vdso.so.1 =>  (0x00007ffe271e6000)
        libcudart.so.7.5 => /usr/local/cuda/lib64/libcudart.so.7.5 (0x00007f96c0807000)
        libwarpctc.so => /home/sarunac4/baidu/warp-ctc/build/libwarpctc.so (0x00007f96c0450000)
        libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f96c014c000)
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f96bfe46000)
        libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f96bfc30000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f96bf86b000)
        libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f96bf667000)
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f96bf449000)
        librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f96bf241000)
        libgomp.so.1 => /usr/lib/x86_64-linux-gnu/libgomp.so.1 (0x00007f96bf032000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f96c0a65000)
But when I try running ./test_gpu I get the error
Running GPU tests
terminate called after throwing an instance of 'thrust::system::system_error'
  what():  cudaSetDevice: unknown error
Aborted (core dumped)

I am running on Ubuntu 14.04, with a TitanX GPU and have the NVIDIA driver version 352.63 installed, any help would be appreciated.

Regards,
Deepak Kadetotad
PhD Student

**Comment by Arseny-N** [comment]
Hi, I have the same issue, how did you solve yours ?
