### ISSUE TITLE
Building error, OpenBlas

### ISSUE THREAD

**Issue by EgorLakomkin** [baidu-research/warp-ctc#67]
```
make[2]: *** No rule to make target `/opt/OpenBLAS/lib/libopenblas.so', needed by `libwarpctc.so'.  Stop.
make[1]: *** [CMakeFiles/warpctc.dir/all] Error 2
make: *** [all] Error 2
```

I have OpenBLAS installed not in /opt/OpenBLAS/lib, but in the other local folder (i do not have root access). Is it possible to specify where the lib should look for openblas?

**Comment by jaredcasper** [comment]
Are you using an unmodified clone of warp-ctc?  That path is not in the sources so would have probably come from a cmake invocation... except that warp-ctc doesn't use any blas libraries and CMakeLists.txt doesn't even look for it.  So I'm not sure why your Makefile has a dependency on libopenblas.so or where it got that path for it.

**Comment by EgorLakomkin** [comment]
Yes, I have used the original library and was also surpirsed as there were no openblas dependency. But the weird thing is that now I cannot reproduce this behaviour. Thank you for your help, anyway!
