### ISSUE TITLE
make error on mac osx 10.12

### ISSUE THREAD

**Issue by aaronshan** [baidu-research/warp-ctc#68]
Hi, when I make warp-ctc on mac osx 10.12, I get this error:
```
nvcc fatal   : The version ('80000') of the host compiler ('Apple clang') is not supported
```
My xcode version is `8.2.1`. Except downgrade my xcode version, how can I solve this problem?

Thanks for your replay.

**Comment by kashif** [comment]
@aaronshan upgrade your cuda toolkit, version 8.0.55 supports the new clang.

**Comment by aaronshan** [comment]
@kashif  thanks. I upgrade cuda to  `8.0.57`,  but it also get this error when I make it
<img width="668" alt="cuda-version-mac" src="https://cloud.githubusercontent.com/assets/5170947/22182369/e3336e64-e0de-11e6-911a-3d3d599e21a7.png">
