### ISSUE TITLE
Will you plan to release fast RNN (LSTM), along bindings for torch?

### ISSUE THREAD

**Issue by jundeng86** [baidu-research/warp-ctc#7]
Really thanks for sharing. But the warp-ctc is a small part of the algorithm ( I mean end-to-end asr system), without the RNN part, it is really hard to use it. To really ease the pain, will you plan to release the RNN implementation?

**Comment by bryancatanzaro** [comment]
We are not planning on releasing a full end-to-end ASR system as part of this project.
