### ISSUE TITLE
能做做国际化吗， 给个中文页面好不好

### ISSUE THREAD

**Issue by name327** [baidu-research/warp-ctc#8]
能做做国际化吗， 给个中文页面好不好

**Comment by qigebixia** [comment]
好好学英语

**Comment by bshillingford** [comment]
他們的API很簡單，你只要看 torch_binding/binding.cpp 或這個fork的example:
https://github.com/sherjilozair/warp-ctc/commit/dd4714c148b3c3164c4389074e3b2661a2bdffd4
(L178-199)

**Comment by sherjilozair** [comment]
@bshillingford, there's a small bug in the interfacing code you linked to. `cost` should actually be an array of size `minibatch`. The code works only if minibatch==1. I'm working on a simpler interface and numpy bindings to increase accessibility.

**Comment by knightliao** [comment]
支持

**Comment by thundertrick** [comment]
国际化不就是英文么？

**Comment by tianwu51** [comment]
我们的torch教程已经有中文版，请见https://github.com/baidu-research/warp-ctc/blob/master/torch_binding/TUTORIAL.zh_cn.md。有关Warp-CTC的中文介绍将会马上上线，欢迎大家指正。

**Comment by tianwu51** [comment]
有关Warp-CTC的中文介绍将会马上上线，欢迎大家指正。我们的torch教程已经有中文版，请见https://github.com/baidu-research/warp-ctc/blob/master/torch_binding/TUTORIAL.zh_cn.md。

**Comment by tianwu51** [comment]
@name327 @knightliao 有关Warp-CTC的中文介绍将会马上上线，欢迎大家指正。我们的torch教程已经有中文版，请见https://github.com/baidu-research/warp-ctc/blob/master/torch_binding/TUTORIAL.zh_cn.md。

**Comment by cyshi** [comment]
@tianwu51 连接最后的标点请去掉 不然点不开

**Comment by tianwu51** [comment]
@cyshi @name327 @knightliao https://github.com/baidu-research/warp-ctc/blob/master/torch_binding/TUTORIAL.zh_cn.md

**Comment by tianwu51** [comment]
@name327 @knightliao 有关Warp-CTC的中文介绍将会马上上线，欢迎大家指正。我们的torch教程已经有中文版，请见https://github.com/baidu-research/warp-ctc/blob/master/torch_binding/TUTORIAL.zh_cn.md

**Comment by ekelsen** [comment]
https://github.com/baidu-research/warp-ctc/blob/master/torch_binding/TUTORIAL.zh_cn.md
https://github.com/baidu-research/warp-ctc/blob/master/README.zh_cn.md
