### ISSUE TITLE
Installation error！recipe for target 'test_gpu' failed！

### ISSUE THREAD

**Issue by wjbKimberly** [baidu-research/warp-ctc#82]
Hi！
When I install warp-ctc following the guide：
git clone https://github.com/baidu-research/warp-ctc.git
cd warp-ctc
mkdir build; cd build
cmake ..
make

I tried to make but problem occurs as shown in Figure！
![2017-06-03 19-15-11](https://cloud.githubusercontent.com/assets/23569606/26753082/18a606f0-4891-11e7-93a6-a25d053dc1ce.png)

May anybody help me?

**Comment by changss** [comment]
@wjbKimberly how fix this issue？I have same problem  with you.

**Comment by littleforce163** [comment]
same to me, anyone would help to fix it?
